mybatis:
  #  type-aliases-package: com.example.transaction.dao
  mapper-locations: classpath:/mapper/*.xml
server:
  port: 8081
spring:
#  application:
#    name: rest-provider

#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848


    sentinel:
      transport:
        dashboard: 127.0.0.1:8002
# 后面的bean会覆盖前面相同名称的bean,暂时方案
#  main:
#    allow-bean-definition-overriding: true


dubbo:
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
      name: rest
      port: 8080
      server: tomcat
  service:
    - interface: modelprovider.service.api.ServiceRest
      protocol: rest, dubbo
      ref: serviceRest
userService:
  class: modelprovider.service.impl.ServiceRestImpl