mybatis:
  #  type-aliases-package: com.example.transaction.dao
  mapper-locations: classpath:/mapper/*.xml
spring:
  application:
    name: model-mzc
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: 2e16a0d0-f9e4-4f11-aba1-68557bdb93a5
# 后面的bean会覆盖前面相同名称的bean,暂时方案
#  main:
#    allow-bean-definition-overriding: true
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    namespace: 2e16a0d0-f9e4-4f11-aba1-68557bdb93a5