mybatis:
  #  type-aliases-package: com.example.transaction.dao
  mapper-locations: classpath:/mapper/*.xml
spring:
  application:
    name: model_mzc
  cloud:
    nacos:
      server-addr: nacos://127.0.0.1:8848


    sentinel:
      transport:
        dashboard: 127.0.0.1:8002
# 后面的bean会覆盖前面相同名称的bean,暂时方案
#  main:
#    allow-bean-definition-overriding: true


#只需在生产者配置即可，不需要在消费者配置，所以不在此配置
#dubbo:
#  registry:
#    address: nacos://127.0.0.1:8848
#    id: model_mzc
#  application:
#    name: model_mzc
