server:
  port: 8007

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        namespace: 2e16a0d0-f9e4-4f11-aba1-68557bdb93a5
    gateway:
      discovery:
        locator:
          enabled: true  #开启通过服务中心的自动根据 serviceId 创建路由的功能
      routes:
        - id: mdx-shop-user             #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://127.0.0.1:8080    #匹配后提供服务的路由地址
          predicates:
            - Path=/service/test      #断言，路径相匹配的进行路由
#    固定路由配置
#      routes:
#        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://127.0.0.1:8080        #匹配后提供服务的路由地址
#          order: 1  # 路由的优先级,数字越小级别越高
#          predicates:
#            - Path=/service/test        # 断言，路径相匹配的进行路由
#gateway:
#  routes:
#    config:
#      data-id: gateway-routes  #动态路由
#      group: DEFAULT_GROUP
#      namespace: public

